name: basic_business_card_2
description: "This Is A Simple Business Card With Basic And Important Widgets."
publish_to: "none"
version: 1.0.0+1
homepage: https://github.com/KASRA10/basic_business_card_2.git
issue_tracker: https://github.com/KASRA10/basic_business_card_2.git
documentation: https://github.com/KASRA10/basic_business_card_2.git
repository: https://github.com/KASRA10/basic_business_card_2.git

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/

  fonts:
    - family: Playwrite
      fonts:
        - asset: lib/fonts/Playwrite.ttf
          style: normal
